name: Primer workflow

on: push

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Hola mundo Actions"

      - name: Bajar código
        uses: actions/checkout@v5

      - name: Probar código
        run: python3 main.py

      - name: Crear imagen Docker
        run: docker build -t IbaiO/holamundo

      - name: Probar contenedor Docker
        run: docker run IbaiO/holamundo
